// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions

const dynamic glo = /** @type {any} */ (typeof globalThis !== 'undefined';

const String importIdentifier = '__ $YJS$ __';

