name: js_to_dart_transpiler
description: A transpiler to convert Y.js JavaScript code to Dart syntax
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # For parsing JavaScript AST
  source_span: ^1.10.0
  # For command line interface
  args: ^2.4.2
  # For file operations
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0