// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions


import 'polyfill.dart';

class YXmlEvent extends YEvent {
  constructor(dynamic target, dynamic subs, dynamic transaction)   constructor (target, subs, transaction) {
    super(target, transaction)
    /**
     * Whether the children changed.
     * @type {Boolean}
     * @private
     */
    this.childListChanged = false
    /**
     * Set of all changed attributes.
     * @type {Set<string>}
     */
    this.attributesChanged = <dynamic>{}
    subs.forEach((sub) => {
      if (sub == null) {
        this.childListChanged = true
      } else {
        this.attributesChanged.add(sub)
      }
    })
  }


}


