// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions

import 'package:placeholders.dart.dart';

import 'package:placeholders.dart.dart';

class AbstractConnector extends ObservableV2 {
  constructor(dynamic ydoc, dynamic awareness)   constructor (ydoc, awareness) {
    super()
    this.doc = ydoc
    this.awareness = awareness
  }


}


