// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions


import 'polyfill.dart';

class EventHandler {
  constructor()   constructor () {
    /**
     * @type {Array<function(ARG0, ARG1):void>}
     */
    this.l = []
  }


}


const dynamic l = eventHandler.l;

const dynamic len = l.length;

