// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions

/// Y.js ID class - transpiled from JavaScript
/// Represents a unique identifier with client and clock components
class ID {
  /// Client id
  final int client;
  
  /// Unique per client id, continuous number
  final int clock;
  
  ID(this.client, this.clock);
  
  @override
  bool operator ==(Object other) {
    return other is ID && other.client == client && other.clock == clock;
  }
  
  @override
  int get hashCode => Object.hash(client, clock);
  
  @override
  String toString() => 'ID($client:$clock)';
}

/// Create an ID from client and clock values (Y.js createID function)
ID createID(int client, int clock) {
  return ID(client, clock);
}

/// Compare two IDs (Y.js compareIDs function)
/// Returns -1 if a < b, 0 if a == b, 1 if a > b
int compareIDs(ID? a, ID? b) {
  if (a == null && b == null) return 0;
  if (a == null) return -1;
  if (b == null) return 1;
  
  // Compare by client first, then by clock
  final clientCompare = a.client.compareTo(b.client);
  if (clientCompare != 0) return clientCompare;
  
  return a.clock.compareTo(b.clock);
}

/// Check if ID a is equal to ID b (Y.js equalIDs function)
bool equalIDs(ID? a, ID? b) {
  return compareIDs(a, b) == 0;
}