// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions


import 'polyfill.dart';

const List<dynamic> res = <dynamic>[];

dynamic n = type._start;

