// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions

import 'package:placeholders.dart.dart';

import 'package:placeholders.dart.dart';

class AbstractStruct {
  dynamic * This method is already assuming that `this.id.clock + this.length = ;

  constructor(String id, int length)   constructor (id, length) {
    this.id = id
    this.length = length
  }


  void deleted()   get deleted () {
    throw error.methodUnimplemented()
  }


  bool mergeWith(dynamic right)   mergeWith (right) {
    return false
  }


  void write(dynamic encoder, int offset, dynamic encodingRef)   write (encoder, offset, encodingRef) {
    throw error.methodUnimplemented()
  }


  void integrate(dynamic transaction, int offset)   integrate (transaction, offset) {
    throw error.methodUnimplemented()
  }


  dynamic import(dynamic '../internals.js')    * @return {import('../internals.js').GC|import('../internals.js').Item}


  void splice(dynamic diff)   splice (diff) {
    throw error.methodUnimplemented()
  }


}


