// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions



import 'polyfill.dart';

class ContentFormat {
  constructor(String key, dynamic value)   constructor (key, value) {
    this.key = key
    this.value = value
  }


  dynamic getLength()   getLength () {
    return 1
  }


  dynamic getContent()   getContent () {
    return []
  }


  bool isCountable()   isCountable () {
    return false
  }


  dynamic copy()   copy () {
    return new ContentFormat(this.key, this.value)
  }


  void splice(int _offset)   splice (_offset) {
    throw error.methodUnimplemented()
  }


  bool mergeWith(dynamic _right)   mergeWith (_right) {
    return false
  }


  void integrate(dynamic _transaction, dynamic item)   integrate (_transaction, item) {
    // @todo searchmarker are currently unsupported for rich text documents
    const p = /** @type {YText<any>} */ (item.parent)
    p._searchMarker = null
    p._hasFormatting = true
  }


  void delete(dynamic _transaction)   delete (_transaction) {}


  void gc(dynamic _tr)   gc (_tr) {}


  void write(dynamic encoder, int _offset, int _offsetEnd)   write (encoder, _offset, _offsetEnd) {
    encoder.writeKey(this.key)
    encoder.writeJSON(this.value)
  }


  dynamic getRef()   getRef () {
    return 6
  }


}


const dynamic p = /** @type {YText<any>} */ (item.parent);

