// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions



import 'polyfill.dart';

class ContentEmbed {
  constructor(dynamic embed)   constructor (embed) {
    this.embed = embed
  }


  dynamic getLength()   getLength () {
    return 1
  }


  dynamic getContent()   getContent () {
    return [this.embed]
  }


  bool isCountable()   isCountable () {
    return true
  }


  dynamic copy()   copy () {
    return new ContentEmbed(this.embed)
  }


  void splice(int offset)   splice (offset) {
    throw error.methodUnimplemented()
  }


  bool mergeWith(dynamic right)   mergeWith (right) {
    return false
  }


  void integrate(dynamic transaction, dynamic item)   integrate (transaction, item) {}


  void delete(dynamic transaction)   delete (transaction) {}


  void gc(dynamic _tr)   gc (_tr) {}


  void write(dynamic encoder, int _offset, int _offsetEnd)   write (encoder, _offset, _offsetEnd) {
    encoder.writeJSON(this.embed)
  }


  dynamic getRef()   getRef () {
    return 5
  }


}


