// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions

import 'package:placeholders.dart.dart';

import 'package:placeholders.dart.dart';

class ContentBinary {
  constructor(dynamic content)   constructor (content) {
    this.content = content
  }


  dynamic getLength()   getLength () {
    return 1
  }


  dynamic getContent()   getContent () {
    return [this.content]
  }


  bool isCountable()   isCountable () {
    return true
  }


  dynamic copy()   copy () {
    return new ContentBinary(this.content)
  }


  void splice(int offset)   splice (offset) {
    throw error.methodUnimplemented()
  }


  bool mergeWith(dynamic right)   mergeWith (right) {
    return false
  }


  void integrate(dynamic transaction, dynamic item)   integrate (transaction, item) {}


  void delete(dynamic transaction)   delete (transaction) {}


  void gc(dynamic _tr)   gc (_tr) {}


  void write(dynamic encoder, int _offset, int _offsetEnd)   write (encoder, _offset, _offsetEnd) {
    encoder.writeBuf(this.content)
  }


  dynamic getRef()   getRef () {
    return 3
  }


}


