// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions


import 'polyfill.dart';

class ContentDeleted {
  constructor(dynamic len)   constructor (len) {
    this.len = len
  }


  dynamic getLength()   getLength () {
    return this.len
  }


  dynamic getContent()   getContent () {
    return []
  }


  bool isCountable()   isCountable () {
    return false
  }


  dynamic copy()   copy () {
    return new ContentDeleted(this.len)
  }


  dynamic splice(int offset)   splice (offset) {
    const right = new ContentDeleted(this.len - offset)
    this.len = offset
    return right
  }


  bool mergeWith(dynamic right)   mergeWith (right) {
    this.len += right.len
    return true
  }


  void integrate(dynamic transaction, dynamic item)   integrate (transaction, item) {
    addToIdSet(transaction.deleteSet, item.id.client, item.id.clock, this.len)
    item.markDeleted()
  }


  void delete(dynamic _transaction)   delete (_transaction) {}


  void gc(dynamic _tr)   gc (_tr) {}


  void write(dynamic encoder, int offset, int offsetEnd)   write (encoder, offset, offsetEnd) {
    encoder.writeLen(this.len - offset - offsetEnd)
  }


  dynamic getRef()   getRef () {
    return 1
  }


}


const dynamic right = ContentDeleted(this.len - offset);

