// Generated by JavaScript-to-Dart transpiler
// Manual implementation may be required for placeholder functions

import 'package:placeholders.dart.dart';

import 'package:placeholders.dart.dart';

class Skip extends AbstractStruct {
  bool deleted()   get deleted () {
    return false
  }


  void delete()   delete () {}


  bool mergeWith(dynamic right)   mergeWith (right) {
    if (this.constructor != right.constructor) {
      return false
    }
    this.length += right.length
    return true
  }


  void integrate(dynamic transaction, int offset)   integrate (transaction, offset) {
    if (offset > 0) {
      this.id.clock += offset
      this.length -= offset
    }
    addToIdSet(transaction.doc.store.skips, this.id.client, this.id.clock, this.length)
    addStruct(transaction.doc.store, this)
  }


  void write(dynamic encoder, int offset)   write (encoder, offset) {
    encoder.writeInfo(structSkipRefNumber)
    // write as VarUint because Skips can't make use of predictable length-encoding
    encoding.writeVarUint(encoder.restEncoder, this.length - offset)
  }


  void getMissing(dynamic _transaction, dynamic _store)   getMissing (_transaction, _store) {
    return null
  }


  dynamic splice(dynamic diff)   splice (diff) {
    const other = new Skip(createID(this.id.client, this.id.clock + diff), this.length - diff)
    this.length = diff
    return other
  }


}


const dynamic other = Skip(createID(this.id.client, this.id.clock + diff), this.length - diff);

